comments:
  service: giscus
  # giscus
  # https://giscus.app/zh-CN
  giscus:
    data-repo: bijinfeng/bijinfeng.github.io
    data-repo-id: R_kgDOHlXKwQ
    data-category: Announcements
    data-category-id: DIC_kwDOHlXKwc4CT421
    data-mapping: pathname
    data-strict: 0
    data-reactions-enabled: 1
    data-emit-metadata: 0
    data-input-position: top # top, bottom
    data-theme: preferred_color_scheme
    data-lang: zh-CN
    data-loading: lazy
    crossorigin: anonymous
